### ISSUE TITLE
Redact passwords on parameter dump

### ISSUE THREAD

**Issue by nuriel77** [iotaledger/hornet#16]
**Describe the bug**
On startup hornet dumps all loaded parameters but this includes authentication passwords, e.g.:
```
 api:
  auth:
    password: verysecret
    username: admin
```
And:
```
  basic_auth:
    enabled: false
    password: verysecret
    username: admin
```

**To Reproduce**
- Just enter a password/username in the config
- Restart hornet
- Check output

**Expected behavior**
Passwords and sensitive data should be redacted in the output, as users can be sending logs remotely or to less secure environments.

**Environment information:**
 - HORNET version 0.2.1

**Additional context**
I tell this to devs at my work all the time 😂
